#!/usr/bin/env python3
"""Generate sizing, cost, and selection evidence tables/figures for the hopper propellant notebook.

This script consumes RocketCEA outputs generated by optimize_cea.py and adds the
system-level evidence used by notebook.typ. It intentionally keeps procurement/pricing
as planning assumptions: industrial gas pricing is quote- and location-dependent.
"""
from __future__ import annotations

import math
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

G0 = 9.80665
RUN_TIME_S = 60.0
THRUST_CASES_N = [200.0, 400.0]
# Planning densities and gas assumptions.
DENSITY = {
    'N2O_liquid_20C_kg_m3': 750.0,        # saturated liquid, approximate planning value
    'GOX_storage_293K_2200psia_kg_m3': None,
    'IPA_kg_m3': 786.0,
    'Ethanol_kg_m3': 789.0,
}
R_O2 = 259.84  # J/(kg*K)
P_STORAGE_PA = 2200.0 * 6894.757293168361
T_STORAGE_K = 293.15
DENSITY['GOX_storage_293K_2200psia_kg_m3'] = P_STORAGE_PA/(R_O2*T_STORAGE_K)
ULLAGE = {'N2O': 1.20, 'GOX': 1.05}
FUEL_DENSITY = {'IPA': DENSITY['IPA_kg_m3'], 'Ethanol': DENSITY['Ethanol_kg_m3']}

# Representative planning prices; replace with local quotes before procurement.
PRICE = {
    'N2O': (10.0, 20.0),        # USD/kg, 10-lb/bulk cylinder refill planning range
    'GOX': (5.0, 12.0),         # USD/kg gas only, welding oxygen refill planning range
    'IPA': (6.0, 13.0),         # USD/kg, 99% gallon/5-gal retail planning range
    'Ethanol': (20.0, 45.0),    # USD/kg, 200-proof/denatured anhydrous planning range
    'Peroxide85': (20.0, 60.0), # USD/kg quote-only hazardous oxidizer placeholder
}

HARDWARE = {
    'N2O': {
        'storage_hardware_usd_low': 200,
        'storage_hardware_usd_high': 650,
        'notes': 'DOT nitrous cylinder(s), compatible valve, relief device, fill adapter; no oxidizer pressure regulator in baseline self-pressurized feed.'
    },
    'GOX': {
        'storage_hardware_usd_low': 650,
        'storage_hardware_usd_high': 1400,
        'notes': 'Oxygen cylinder or custom high-pressure gas vessel, CGA-540 hardware, high-flow oxygen-clean regulator, relief hardware, oxygen-clean fittings.'
    },
    'Peroxide85': {
        'storage_hardware_usd_low': 500,
        'storage_hardware_usd_high': 1500,
        'notes': 'Peroxide-compatible tank and valves, catalyst or ignition hardware, strict material compatibility controls, hazardous shipping/handling overhead.'
    },
}

def ox_family(case: str) -> str:
    if case.startswith('N2O'): return 'N2O'
    if case.startswith('GOX'): return 'GOX'
    if case.startswith('Peroxide85'): return 'Peroxide85'
    if case.startswith('Peroxide70'): return 'Peroxide70'
    return 'unknown'

def fuel_family(case: str) -> str:
    if 'IPA' in case: return 'IPA'
    if 'Ethanol' in case: return 'Ethanol'
    if 'Methanol' in case: return 'Methanol'
    return 'unknown'

def sizing_rows(summary: pd.DataFrame) -> pd.DataFrame:
    rows=[]
    for _, r in summary.iterrows():
        case = r['case']
        ox = ox_family(case)
        fuel = fuel_family(case)
        if ox not in {'N2O','GOX','Peroxide85'} or fuel not in {'IPA','Ethanol'}:
            continue
        for thrust in THRUST_CASES_N:
            isp = float(r['isp_amb_s'])
            mr = float(r['mr'])
            total = thrust/(isp*G0)*RUN_TIME_S
            mox = total*mr/(1+mr)
            mfuel = total/(1+mr)
            if ox == 'N2O':
                vox = mox/DENSITY['N2O_liquid_20C_kg_m3']*1000
                vox_w = vox*ULLAGE['N2O']
            elif ox == 'GOX':
                vox = mox/DENSITY['GOX_storage_293K_2200psia_kg_m3']*1000
                vox_w = vox*ULLAGE['GOX']
            else:
                # 85% H2O2 solution density varies by supplier/stabilizer; use 1.34 g/mL planning value.
                vox = mox/1340.0*1000
                vox_w = vox*1.10
            vfuel = mfuel/FUEL_DENSITY[fuel]*1000
            ox_price = PRICE.get(ox, (0,0))
            fuel_price = PRICE.get(fuel, (0,0))
            prop_low = mox*ox_price[0] + mfuel*fuel_price[0]
            prop_high = mox*ox_price[1] + mfuel*fuel_price[1]
            hw = HARDWARE.get(ox, {'storage_hardware_usd_low': None, 'storage_hardware_usd_high': None, 'notes': ''})
            rows.append({
                'case': case,
                'thrust_N': thrust,
                'burn_s': RUN_TIME_S,
                'isp_sl_s': isp,
                'of_ratio': mr,
                'total_propellant_kg': total,
                'oxidizer_kg': mox,
                'fuel_kg': mfuel,
                'oxidizer_storage_volume_L': vox,
                'oxidizer_storage_volume_with_margin_L': vox_w,
                'fuel_volume_L': vfuel,
                'propellant_cost_low_usd': prop_low,
                'propellant_cost_high_usd': prop_high,
                'storage_hardware_usd_low': hw['storage_hardware_usd_low'],
                'storage_hardware_usd_high': hw['storage_hardware_usd_high'],
                'hardware_notes': hw['notes'],
            })
    return pd.DataFrame(rows)

def make_plots(outdir: Path, summary: pd.DataFrame, sizing: pd.DataFrame) -> None:
    fig_dir = outdir/'figures'
    data_dir = outdir/'data'
    fig_dir.mkdir(parents=True, exist_ok=True)
    finalists = ['N2O_IPA','N2O_Ethanol','GOX_IPA','GOX_Ethanol']
    # Combined O/F vs ambient Isp plot
    fig, ax = plt.subplots(figsize=(8.5,5.2))
    for case in finalists:
        f = data_dir/f'{case}_equilibrium_pc150.csv'
        df = pd.read_csv(f).dropna(subset=['isp_amb_s'])
        ax.plot(df['mr'], df['isp_amb_s'], linewidth=2, label=case.replace('_','/'))
    ax.set_xlabel('Mixture ratio O/F (mass)')
    ax.set_ylabel('Sea-level ambient-corrected Isp (s)')
    ax.set_title('Finalist O/F sensitivity at Pc=150 psia, Pamb=14.7 psia')
    ax.grid(True, linestyle=':', alpha=0.6)
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(fig_dir/'finalist_of_vs_isp_combined.png', dpi=200)
    plt.close(fig)

    # Individual plots with oxidizer mass for 200N/60s shown on secondary axis.
    for case in finalists:
        f = data_dir/f'{case}_equilibrium_pc150.csv'
        df = pd.read_csv(f).dropna(subset=['isp_amb_s']).copy()
        df['total_prop_200N_60s_kg'] = 200.0/(df['isp_amb_s']*G0)*RUN_TIME_S
        df['oxidizer_kg_200N_60s'] = df['total_prop_200N_60s_kg']*df['mr']/(1+df['mr'])
        fig, ax1 = plt.subplots(figsize=(8,4.8))
        ax1.plot(df['mr'], df['isp_amb_s'], linewidth=2)
        ax1.set_xlabel('Mixture ratio O/F (mass)')
        ax1.set_ylabel('Sea-level Isp (s)')
        ax1.grid(True, linestyle=':', alpha=0.6)
        ax2 = ax1.twinx()
        ax2.plot(df['mr'], df['oxidizer_kg_200N_60s'], linewidth=1.5, linestyle='--')
        ax2.set_ylabel('Oxidizer required for 200 N, 60 s (kg)')
        best = summary[summary['case']==case].iloc[0]
        ax1.axvline(best['mr'], linestyle=':', linewidth=1)
        ax1.set_title(f'{case.replace("_","/")}: O/F performance vs oxidizer requirement')
        fig.tight_layout()
        fig.savefig(fig_dir/f'{case}_of_isp_and_oxidizer_mass.png', dpi=200)
        plt.close(fig)

    # Cost ranges at 200N and 400N.
    for thrust in THRUST_CASES_N:
        sub = sizing[(sizing['thrust_N']==thrust) & (sizing['case'].isin(finalists))].copy()
        sub = sub.set_index('case').loc[finalists].reset_index()
        x = np.arange(len(sub))
        low = sub['propellant_cost_low_usd']
        high = sub['propellant_cost_high_usd']
        fig, ax = plt.subplots(figsize=(8,4.8))
        ax.bar(x, high-low, bottom=low)
        ax.scatter(x, low, marker='_')
        ax.scatter(x, high, marker='_')
        ax.set_xticks(x)
        ax.set_xticklabels([c.replace('_','/') for c in sub['case']], rotation=20, ha='right')
        ax.set_ylabel('Propellant consumables per 60 s test (USD)')
        ax.set_title(f'Representative propellant cost range, {int(thrust)} N / 60 s')
        ax.grid(True, axis='y', linestyle=':', alpha=0.6)
        fig.tight_layout()
        fig.savefig(fig_dir/f'propellant_cost_range_{int(thrust)}N_60s.png', dpi=200)
        plt.close(fig)

    # Oxidizer storage volume comparison.
    fig, ax = plt.subplots(figsize=(8,4.8))
    sub = sizing[(sizing['thrust_N']==200) & (sizing['case'].isin(finalists))].set_index('case').loc[finalists].reset_index()
    x = np.arange(len(sub))
    width=0.35
    ax.bar(x-width/2, sub['oxidizer_storage_volume_with_margin_L'], width, label='200 N / 60 s')
    sub2 = sizing[(sizing['thrust_N']==400) & (sizing['case'].isin(finalists))].set_index('case').loc[finalists].reset_index()
    ax.bar(x+width/2, sub2['oxidizer_storage_volume_with_margin_L'], width, label='400 N / 60 s')
    ax.set_xticks(x)
    ax.set_xticklabels([c.replace('_','/') for c in sub['case']], rotation=20, ha='right')
    ax.set_ylabel('Oxidizer storage volume incl. margin (L)')
    ax.set_title('Oxidizer storage volume penalty: GOX gas vs N2O liquid')
    ax.grid(True, axis='y', linestyle=':', alpha=0.6)
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(fig_dir/'oxidizer_storage_volume_comparison.png', dpi=200)
    plt.close(fig)

    # Selection score plot
    scores = pd.read_csv(outdir/'data'/'selection_matrix.csv')
    fig, ax = plt.subplots(figsize=(8,4.6))
    ax.bar(np.arange(len(scores)), scores['weighted_score'])
    ax.set_xticks(np.arange(len(scores)))
    ax.set_xticklabels(scores['case'], rotation=20, ha='right')
    ax.set_ylabel('Weighted score (0-5)')
    ax.set_title('Propellant architecture selection score')
    ax.set_ylim(0,5)
    ax.grid(True, axis='y', linestyle=':', alpha=0.6)
    fig.tight_layout()
    fig.savefig(fig_dir/'selection_weighted_score.png', dpi=200)
    plt.close(fig)

def make_selection_matrix(outdir: Path) -> pd.DataFrame:
    weights = {
        'safety_and_access': 0.20,
        'consumable_and_hardware_cost': 0.15,
        'storage_mass_volume': 0.15,
        'feed_control_predictability': 0.15,
        'development_risk': 0.15,
        'direct_heritage': 0.10,
        'performance': 0.05,
        'cooling_material_margin': 0.05,
    }
    rows = [
        # Scores are 0-5 where 5 is best for this hopper design. They are intentionally architecture-level, not pure performance rankings.
        ('N2O/IPA',      4.0, 4.5, 4.0, 2.5, 2.5, 5.0, 3.0, 3.5, 'Selected baseline: compact oxidizer storage and strongest VTVL analog; two-phase injector risk is the dominant development item.'),
        ('N2O/Ethanol',  3.5, 3.5, 4.0, 2.5, 2.5, 4.0, 3.0, 4.5, 'Backup: best N2O/alcohol literature and cooling conductivity; less convenient fuel procurement.'),
        ('GOX/Ethanol',  3.0, 2.0, 1.5, 4.5, 4.5, 3.0, 4.5, 4.5, 'Alternate if two-phase N2O is unacceptable; gas storage and oxygen hardware dominate cost/mass.'),
        ('GOX/IPA',      3.0, 2.5, 1.5, 4.5, 4.5, 2.0, 5.0, 3.5, 'Valid GOX alternate; slightly better computed Isp but less directly validated than GOX/ethanol.'),
        ('85% H2O2/IPA', 1.5, 1.5, 5.0, 2.5, 2.0, 1.0, 3.0, 2.0, 'Near miss only: compact and similar Isp, but oxidizer access, decomposition, catalyst/ignition, and compatibility risks are severe.'),
    ]
    cols=['case', *weights.keys(), 'selection_note']
    df=pd.DataFrame(rows, columns=cols)
    df['weighted_score'] = sum(df[k]*w for k,w in weights.items())
    df['weighted_score'] = df['weighted_score'].round(2)
    df.sort_values('weighted_score', ascending=False).to_csv(outdir/'data'/'selection_matrix.csv', index=False)
    # write weights as csv too
    pd.DataFrame([{'criterion':k, 'weight':v} for k,v in weights.items()]).to_csv(outdir/'data'/'selection_weights.csv', index=False)
    return df.sort_values('weighted_score', ascending=False)


def main():
    outdir = Path('rocket_outputs')
    summary = pd.read_csv(outdir/'data'/'batch_optimum_summary.csv')
    sizing = sizing_rows(summary)
    sizing.to_csv(outdir/'data'/'system_sizing_and_cost_summary.csv', index=False)

    price_rows=[]
    for name,(lo,hi) in PRICE.items():
        price_rows.append({'item': name, 'planning_price_low_usd_per_kg': lo, 'planning_price_high_usd_per_kg': hi})
    pd.DataFrame(price_rows).to_csv(outdir/'data'/'propellant_price_assumptions.csv', index=False)
    make_selection_matrix(outdir)
    make_plots(outdir, summary, sizing)

if __name__ == '__main__':
    main()
